const ROUTES = {
  HOME: "/home",
  LOGIN: "/login",
  SIGNUP: "/signup",
  PAYMENTS: "/payment_page",
  PACKAGE: "/package_page",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  BUSINESS_LOCATIONS: "/business-locations",
  TECHNICIAN: "/technician_onboard_page",
  PROFILE: "/profile/:id", 
  THANKYOU: "/thankyou_page",
  DECLINE: "/decline_page",
  STANDARD:"/standard_page",
  PROFESSIONAL:"/professional_page",
  ENTERPRISE:"/enterprise_page",
  PREMIER:"/premier_page",
  ADDITIONALFEATURE: "/additional_feature_page",
  TERMS:"/terms_page",
  SELECTLOCATION:"/select_location_page",
  FRONTPAGE:"/front_page",
  SETTINGS:"/settings_page",
  CARDS:"/cards_page",
  INVOICE:"/invoice_page",
  UPDATE_PACKAGE:"/update_package_page",
  NEW_PAYMENT:"/new_payment_method_page",
  SELECT_PAYMENT_METHOD: "/select_payment_method_page",
  UPDATE_INVOICE:"/update_invoice_page",
  DRIVE_THRU:"/drive_thru_page",
  DRIVE_THRU_CONTRACT:"/drive_thru_contract_page",
  DRIVE_THRU_INVOICE:"/drive_thru_invoice_page"
};

export default ROUTES;
